# Generated by Django 6.1.1 on 2026-09-24 00:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita (+)'), ('DESPESA', 'Despesa (-)')], default='DESPESA', max_length=10, verbose_name='Tipo de Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Observações')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('tipo', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Poupança'), ('INVESTIMENTO', 'Investimento'), ('CARTEIRA', 'Dinheiro em Espécie / Carteira')], default='CORRENTE', max_length=20, verbose_name='Tipo de Conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo Inicial (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição do Lançamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita (+)'), ('DESPESA', 'Despesa (-)')], default='DESPESA', max_length=10, verbose_name='Tipo')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Lançamento')),
                ('status', models.CharField(choices=[('CONCLUIDO', 'Concluído / Pago'), ('PENDENTE', 'Pendente / A Vencer')], default='CONCLUIDO', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='controle.categoria', verbose_name='Categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='controle.conta', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
